# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'copylist_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CopyListDialog(object):
    def setupUi(self, CopyListDialog):
        CopyListDialog.setObjectName("CopyListDialog")
        CopyListDialog.resize(385, 110)
        CopyListDialog.setMinimumSize(QtCore.QSize(385, 110))
        CopyListDialog.setMaximumSize(QtCore.QSize(385, 110))
        self.verticalLayout = QtWidgets.QVBoxLayout(CopyListDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblNameCopy = QtWidgets.QLabel(CopyListDialog)
        self.lblNameCopy.setMinimumSize(QtCore.QSize(90, 0))
        self.lblNameCopy.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblNameCopy.setFont(font)
        self.lblNameCopy.setObjectName("lblNameCopy")
        self.horizontalLayout.addWidget(self.lblNameCopy)
        self.editNameCopy = QtWidgets.QLineEdit(CopyListDialog)
        self.editNameCopy.setObjectName("editNameCopy")
        self.horizontalLayout.addWidget(self.editNameCopy)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblListCopy = QtWidgets.QLabel(CopyListDialog)
        self.lblListCopy.setMinimumSize(QtCore.QSize(90, 0))
        self.lblListCopy.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblListCopy.setFont(font)
        self.lblListCopy.setObjectName("lblListCopy")
        self.horizontalLayout_2.addWidget(self.lblListCopy)
        self.cmbListCopy = QtWidgets.QComboBox(CopyListDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbListCopy.sizePolicy().hasHeightForWidth())
        self.cmbListCopy.setSizePolicy(sizePolicy)
        self.cmbListCopy.setObjectName("cmbListCopy")
        self.horizontalLayout_2.addWidget(self.cmbListCopy)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(CopyListDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.btnCopy = QtWidgets.QPushButton(CopyListDialog)
        self.btnCopy.setObjectName("btnCopy")
        self.verticalLayout.addWidget(self.btnCopy)

        self.retranslateUi(CopyListDialog)
        QtCore.QMetaObject.connectSlotsByName(CopyListDialog)

    def retranslateUi(self, CopyListDialog):
        _translate = QtCore.QCoreApplication.translate
        CopyListDialog.setWindowTitle(_translate("CopyListDialog", "Dialog"))
        self.lblNameCopy.setText(_translate("CopyListDialog", "Nombre copia:"))
        self.lblListCopy.setText(_translate("CopyListDialog", "Lista a copiar:"))
        self.btnCopy.setText(_translate("CopyListDialog", "Copiar"))
