# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'searching_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SearchingDialog(object):
    def setupUi(self, SearchingDialog):
        SearchingDialog.setObjectName("SearchingDialog")
        SearchingDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        SearchingDialog.resize(380, 105)
        SearchingDialog.setMinimumSize(QtCore.QSize(380, 105))
        SearchingDialog.setMaximumSize(QtCore.QSize(380, 105))
        SearchingDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(SearchingDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblModList = QtWidgets.QLabel(SearchingDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblModList.setFont(font)
        self.lblModList.setObjectName("lblModList")
        self.horizontalLayout_3.addWidget(self.lblModList)
        self.cmbModList = QtWidgets.QComboBox(SearchingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbModList.sizePolicy().hasHeightForWidth())
        self.cmbModList.setSizePolicy(sizePolicy)
        self.cmbModList.setObjectName("cmbModList")
        self.horizontalLayout_3.addWidget(self.cmbModList)
        self.lblPages = QtWidgets.QLabel(SearchingDialog)
        self.lblPages.setMinimumSize(QtCore.QSize(50, 0))
        self.lblPages.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblPages.setFont(font)
        self.lblPages.setObjectName("lblPages")
        self.horizontalLayout_3.addWidget(self.lblPages)
        self.spinPages = QtWidgets.QSpinBox(SearchingDialog)
        self.spinPages.setEnabled(True)
        self.spinPages.setMinimumSize(QtCore.QSize(60, 0))
        self.spinPages.setMaximumSize(QtCore.QSize(60, 16777215))
        self.spinPages.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spinPages.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinPages.setObjectName("spinPages")
        self.horizontalLayout_3.addWidget(self.spinPages)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.btnSearchNewMods = QtWidgets.QPushButton(SearchingDialog)
        self.btnSearchNewMods.setEnabled(False)
        self.btnSearchNewMods.setMinimumSize(QtCore.QSize(0, 23))
        self.btnSearchNewMods.setMaximumSize(QtCore.QSize(16777215, 23))
        self.btnSearchNewMods.setObjectName("btnSearchNewMods")
        self.verticalLayout.addWidget(self.btnSearchNewMods)
        self.line = QtWidgets.QFrame(SearchingDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.progressBar = QtWidgets.QProgressBar(SearchingDialog)
        self.progressBar.setEnabled(True)
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setFormat("%v/%m Procesados")
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)

        self.retranslateUi(SearchingDialog)
        QtCore.QMetaObject.connectSlotsByName(SearchingDialog)

    def retranslateUi(self, SearchingDialog):
        _translate = QtCore.QCoreApplication.translate
        SearchingDialog.setWindowTitle(_translate("SearchingDialog", "Buscar nuevos mods"))
        self.lblModList.setText(_translate("SearchingDialog", "ModList:"))
        self.lblPages.setText(_translate("SearchingDialog", "Paginas:"))
        self.btnSearchNewMods.setText(_translate("SearchingDialog", "Buscar nuevos mods"))
