# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'searching_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SearchingDialog(object):
    def setupUi(self, SearchingDialog):
        SearchingDialog.setObjectName("SearchingDialog")
        SearchingDialog.resize(380, 60)
        SearchingDialog.setMinimumSize(QtCore.QSize(380, 60))
        SearchingDialog.setMaximumSize(QtCore.QSize(380, 60))
        self.verticalLayout = QtWidgets.QVBoxLayout(SearchingDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(SearchingDialog)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.progressBar = QtWidgets.QProgressBar(SearchingDialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setFormat("")
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)

        self.retranslateUi(SearchingDialog)
        QtCore.QMetaObject.connectSlotsByName(SearchingDialog)

    def retranslateUi(self, SearchingDialog):
        _translate = QtCore.QCoreApplication.translate
        SearchingDialog.setWindowTitle(_translate("SearchingDialog", "Dialog"))
        self.label.setText(_translate("SearchingDialog", "TextLabel"))
