# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'searching_mod_id_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SearchModIdDialog(object):
    def setupUi(self, SearchModIdDialog):
        SearchModIdDialog.setObjectName("SearchModIdDialog")
        SearchModIdDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        SearchModIdDialog.resize(188, 69)
        SearchModIdDialog.setMinimumSize(QtCore.QSize(188, 69))
        SearchModIdDialog.setMaximumSize(QtCore.QSize(188, 72))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/widgets/widgets/window_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SearchModIdDialog.setWindowIcon(icon)
        SearchModIdDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(SearchModIdDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblModid = QtWidgets.QLabel(SearchModIdDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblModid.setFont(font)
        self.lblModid.setObjectName("lblModid")
        self.horizontalLayout.addWidget(self.lblModid)
        self.spinModid = QtWidgets.QSpinBox(SearchModIdDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinModid.setFont(font)
        self.spinModid.setAlignment(QtCore.Qt.AlignCenter)
        self.spinModid.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinModid.setMaximum(999999999)
        self.spinModid.setSingleStep(0)
        self.spinModid.setProperty("value", 0)
        self.spinModid.setObjectName("spinModid")
        self.horizontalLayout.addWidget(self.spinModid)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.btnSearch = QtWidgets.QPushButton(SearchModIdDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnSearch.setFont(font)
        self.btnSearch.setObjectName("btnSearch")
        self.verticalLayout.addWidget(self.btnSearch)

        self.retranslateUi(SearchModIdDialog)
        QtCore.QMetaObject.connectSlotsByName(SearchModIdDialog)

    def retranslateUi(self, SearchModIdDialog):
        _translate = QtCore.QCoreApplication.translate
        SearchModIdDialog.setWindowTitle(_translate("SearchModIdDialog", "Buscar mod"))
        self.lblModid.setText(_translate("SearchModIdDialog", "ID del Mod:"))
        self.btnSearch.setText(_translate("SearchModIdDialog", "Buscar"))
import icons_rc
