# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'warning_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WarningDialog(object):
    def setupUi(self, WarningDialog):
        WarningDialog.setObjectName("WarningDialog")
        WarningDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        WarningDialog.resize(94, 97)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WarningDialog.sizePolicy().hasHeightForWidth())
        WarningDialog.setSizePolicy(sizePolicy)
        WarningDialog.setMinimumSize(QtCore.QSize(0, 97))
        WarningDialog.setMaximumSize(QtCore.QSize(16777215, 97))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/widgets/widgets/warning.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WarningDialog.setWindowIcon(icon)
        WarningDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(WarningDialog)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layout = QtWidgets.QHBoxLayout()
        self.layout.setSpacing(0)
        self.layout.setObjectName("layout")
        self.iconAviso = QtWidgets.QLabel(WarningDialog)
        self.iconAviso.setMinimumSize(QtCore.QSize(48, 48))
        self.iconAviso.setMaximumSize(QtCore.QSize(48, 48))
        self.iconAviso.setText("")
        self.iconAviso.setPixmap(QtGui.QPixmap(":/widgets/widgets/warning.png"))
        self.iconAviso.setObjectName("iconAviso")
        self.layout.addWidget(self.iconAviso)
        self.lblAviso = QtWidgets.QLabel(WarningDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblAviso.setFont(font)
        self.lblAviso.setText("")
        self.lblAviso.setObjectName("lblAviso")
        self.layout.addWidget(self.lblAviso)
        self.verticalLayout.addLayout(self.layout)
        self.botones = QtWidgets.QDialogButtonBox(WarningDialog)
        self.botones.setMinimumSize(QtCore.QSize(0, 25))
        self.botones.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.botones.setFont(font)
        self.botones.setOrientation(QtCore.Qt.Horizontal)
        self.botones.setStandardButtons(QtWidgets.QDialogButtonBox.NoButton)
        self.botones.setObjectName("botones")
        self.verticalLayout.addWidget(self.botones)

        self.retranslateUi(WarningDialog)
        self.botones.accepted.connect(WarningDialog.accept) # type: ignore
        self.botones.rejected.connect(WarningDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(WarningDialog)

    def retranslateUi(self, WarningDialog):
        _translate = QtCore.QCoreApplication.translate
        WarningDialog.setWindowTitle(_translate("WarningDialog", "Warning"))
import icons_rc
